# Generated by Django 5.0.6 on 2024-05-22 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_project_date_remove_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Default title', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
