# Generated by Django 5.0.6 on 2024-05-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
