# Generated by Django 5.0.6 on 2024-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='Default title', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='image_details',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
