# Generated by Django 5.0.6 on 2024-05-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_project_category_project_image_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ML', 'Machine Learning'), ('DA', 'Data Analysis'), ('WEB', 'Web'), ('ALL', 'All')], max_length=100),
        ),
    ]
