# Generated by Django 5.0.6 on 2024-05-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_details',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
