# Generated by Django 5.0.6 on 2024-05-23 13:01

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_project_image_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='percentage',
            field=models.PositiveIntegerField(default=50, validators=[blog.models.validate_percentage]),
        ),
        migrations.AddField(
            model_name='project',
            name='skill',
            field=models.CharField(default='Default title', max_length=100),
        ),
    ]
