# Generated by Django 5.0.6 on 2024-05-23 13:12

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_project_percentage_project_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(default=50, validators=[blog.models.validate_percentage])),
                ('skill', models.CharField(default='Default title', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skill',
        ),
    ]
