# Generated by Django 5.0.6 on 2024-05-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_details',
        ),
    ]
