# Generated by Django 5.0.6 on 2024-05-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_project_image_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='image',
            new_name='image_detail',
        ),
    ]
