# Generated by Django 5.0.6 on 2024-05-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_rename_image_projectimage_image_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_detail', models.CharField(default='Default title', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
