# Generated by Django 5.0.6 on 2024-05-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_images_delete_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_detail',
            field=models.ImageField(upload_to='images'),
        ),
    ]
