# Generated by Django 5.0.6 on 2024-05-24 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_images_description_alter_images_image_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date',
            new_name='date1',
        ),
        migrations.AddField(
            model_name='project',
            name='date2',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
