# Generated by Django 5.0.6 on 2024-06-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_remove_certificate_image_detail_certificate_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='title',
        ),
        migrations.AddField(
            model_name='certificate',
            name='image_detail',
            field=models.ImageField(default='images/default.jpg', upload_to='images'),
        ),
    ]
