# Generated by Django 5.0.6 on 2024-06-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_remove_certificate_pdf_remove_certificate_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
