# Generated by Django 5.0.6 on 2024-06-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_certificate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='place',
            field=models.CharField(default='Default title', max_length=100),
        ),
    ]
