# Generated by Django 5.0.6 on 2024-06-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_experience_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='place',
            field=models.CharField(default='Default title', max_length=100),
        ),
    ]
